name: Blocklayer

on: [pull_request,push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy with Blocklayer
      uses: blocklayerhq/actions@alpha-2
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        api_key: "${{ secrets.BL_API_KEY }}"
        pipeline: "docs.particubes.com-pr-${{ github.sha }}"
        clone: "docs.particubes.com"
        inputs: -o git_ref=${{ github.sha }}
