version: '3.1'
services:
  download-dot-particubes:
    image: halverneus/static-file-server:v1.7.2
    container_name: download-dot-particubes
    restart: always
    expose:
      - "80"
    environment:
      - PORT=80
      - FOLDER=/content
    stdin_open: true
    tty: true
