name: Blocklayer

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Blocklayer Deploy
        id: deploy
        uses: blocklayerhq/actions@beta
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          api_key: "${{ secrets.BL_API_KEY }}"
          stack: "particubes"
          env: "prod"
          sources: "docs=./lua-docs"
